# Inherits from docker-compose.yml (via cli)

version: "3.5"
services:
  api:
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn run api:debug

  cron:
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn run cron:debug

  worker:
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn run worker:debug

  socket:
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn run socket:debug
