version: "3.5"
services:
  api:
    container_name: node-starter_api
    build: .
    links:
      - mongo
      - redis
      - s3
    environment:
      - CONFIG_NAME
      - CONFIG_PASSWORD
    ports:
      - "3000:3000"
    command: yarn run api

  cron:
    container_name: node-starter_cron
    build: .
    links:
      - mongo
      - redis
      - s3
    environment:
      - CONFIG_NAME
      - CONFIG_PASSWORD
    command: yarn run cron

  worker:
    container_name: node-starter_worker
    build: .
    links:
      - mongo
      - redis
      - s3
    environment:
      - CONFIG_NAME
      - CONFIG_PASSWORD
    command: yarn run worker

  socket:
    container_name: node-starter_socket
    build: .
    links:
      - mongo
      - redis
      - s3
    environment:
      - CONFIG_NAME
      - CONFIG_PASSWORD
    ports:
      - "3001:3001"
    command: yarn run socket

  mongo:
    container_name: node-starter_mongo
    image: bitnami/mongodb:4.4
    environment:
      - MONGODB_DISABLE_SYSTEM_LOG=true
      - MONGODB_SYSTEM_LOG_VERBOSITY=0
    volumes:
      - ./tmp/data/mongo:/bitnami/mongodb
    ports:
      - '27018:27017'
    logging:
      driver: none

  redis:
    container_name: node-starter_redis
    image: bitnami/redis:6.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./tmp/data/redis:/bitnami/redis/data
    ports:
      - '6380:6379'
    logging:
      driver: none

  s3:
    container_name: node-starter_s3
    image: bitnami/minio:2022.4.30
    environment:
      - MINIO_DEFAULT_BUCKETS=node-starter
    volumes:
      - ./tmp/data/minio:/data
    ports:
      - '9000:9000'
      - '9001:9001'
    logging:
      driver: none
